# Generated by Django 4.1 on 2022-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image1', models.ImageField(null=True, upload_to='Discussion_Forum/upload_img')),
                ('Image2', models.ImageField(null=True, upload_to='Images')),
            ],
            options={
                'verbose_name_plural': 'Test',
                'ordering': ['Name'],
            },
        ),
    ]
