# Generated by Django 4.1 on 2022-09-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0002_remove_test_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Image2',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
