# Generated by Django 4.1 on 2022-09-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0003_test_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Image2',
        ),
    ]
