# Generated by Django 4.1 on 2022-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('userregistration_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userregistration_email_field', models.EmailField(max_length=60, unique=True)),
                ('userregistration_password', models.CharField(max_length=500)),
                ('userregistration_confirm_password', models.CharField(max_length=500)),
                ('registration_User_Type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization'), ('DomainExpert', 'DomainExpert')], default='Individual', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User Registration',
                'ordering': ['userregistration_email_field'],
            },
        ),
    ]
